name: jester com
favicon: null
layout_spectrum: 0.964629135793075
typography_spectrum: 0.03423993941396475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.35050793061964214
  lightness: 0.4231786415912211
  saturation: 0.887540414230898
  rhythmicContrast: 0.23662810935638845
purpose: []
